[build]
  command = "npm run build"
  publish = "dist/public"

[[redirects]]
  from   = "https://www.rex-bedachung.de/*"
  to     = "https://firma.rex-bedachung.de/:splat"
  status = 301
  force  = true
